AllCops:
  Exclude:
    - db/**/*
    - bin/*
    - "**/*.haml"
    - frontend/**/*

  TargetRubyVersion: 2.3

Metrics/LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100
  Exclude:
    - config/initializers/secret_token.rb

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-string-literals'
  EnforcedStyle: double_quotes
  Enabled: true
